### ISSUE TITLE
Unable to destroy cluster when configure_ip_masq is set to true

### ISSUE THREAD

**Issue by mous2890** [terraform-google-modules/terraform-google-kubernetes-engine#627] opened 2020-08-13 11:11 UTC
Currently have 3 GKE clusters built using this module however configure_ip_masq was not enabled. I needed to ensure my pods were having their IPs masq'd and NAT'd to use the Node IP so i found the option to enable ip-masq in GKE. After I enabled configure_ip_masq and applied the terraform plan, i am no longer able to destroy my GKE clusters. 

Here is my terraform with the ip-masq config set:
```
# Module Source
# https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/master/modules/beta-private-cluster-update-variant

module "gke_shared_cluster" {

  source  = "terraform-google-modules/kubernetes-engine/google//modules/beta-private-cluster-update-variant"
  version = "9.2.0"

  project_id = var.project_id
  name       = var.project_name
  regional   = true
  region     = var.region

  # VPC Networking
  network_project_id     = var.vpc_network_project_id
  network                = var.vpc_network_name
  subnetwork             = var.vpc_subnetwork_name
  ip_range_pods          = "${var.vpc_subnetwork_name}-pods"
  ip_range_services      = "${var.vpc_subnetwork_name}-services"
  master_ipv4_cidr_block = var.master_ipv4_cidr_block

  configure_ip_masq    = true
  non_masquerade_cidrs = ["172.0.0.0/8"]

  enable_private_endpoint    = false
  kubernetes_version         = var.kubernetes_version
  identity_namespace         = var.identity_namespace
  remove_default_node_pool   = true
  enable_private_nodes       = true
  add_cluster_firewall_rules = true
  firewall_inbound_ports     = ["8443", "9443", "15017", "8080"] 

  authenticator_security_group = "obfuscated@obfuscated.com"
  pod_security_policy_config = [{
    enabled = true
  }]

  node_pools = var.node_pools

  node_pools_oauth_scopes = {
    all = [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/devstorage.read_only"
    ]
  }

  node_pools_labels = var.node_pools_labels

  node_pools_taints = var.node_pools_taints

  node_pools_metadata = {
    all = {}
  }

  node_pools_tags = {
    all = [
      var.project_id,
      "https-server",
      "ssh-server",
    ]
  }
}
```

When I do a plan and apply, no problems. The GKE cluster gets built correctly. When i do a terraform destroy, the plan is displayed. When I apply the destroy plan, i get the following error:
Note: I've attached the full destroy apply output. 
[tf.txt](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/files/5068642/tf.txt)

```
Error: Cycle: module.gke.module.gke_shared_cluster.local.cluster_output_master_auth, module.gke.module.gke_shared_cluster.local.cluster_master_auth_list_layer1, module.gke.module.gke_shared_cluster.local.cluster_master_auth_list_layer2, module.gke.module.gke_shared_cluster.local.cluster_master_auth_map, module.gke.module.gke_shared_cluster.local.cluster_ca_certificate, module.gke.module.gke_shared_cluster.google_container_cluster.primary (destroy), module.gke.module.gke_shared_cluster.local.cluster_endpoint, module.gke.module.gke_shared_cluster.provider.kubernetes, module.gke.module.gke_shared_cluster.kubernetes_config_map.ip-masq-agent[0] (destroy), module.gke.module.gke_shared_cluster.google_container_node_pool.pools["general"] (destroy)
```

The only way i can delete these GKE clusters is by removing the ip-masq-agent from my cluster and then re-running the destroy and apply. 

Can this be looked into as to why I'm unable to destroy GKE clusters created by this module when configure_ip_masq is enabled?

**Comment by mous2890** [comment] 2020-08-13 13:28
Upgraded to latest version v11.0.0 of the module and the issue persists.

**Comment by bharathkkb** [comment] 2020-08-28 20:32
Hi @mous2890

I was able to successfully reproduce it using tf `0.12.28` when I do it via
```
terraform plan -destroy -out=destroy.tfplan
terraform apply "destroy.tfplan"
```
However a regular `terraform destroy` seems to work fine. It is also worth noting that the above plan and destroy approach seems to be working with `0.13.x`. So this seems like a bug in Terraform `0.12.x`.

**Comment by bharathkkb** [comment] 2020-09-01 17:39
@mous2890 closing this out as it seems to be a bug in TF and we have identified some workarounds. Feel free to reopen if needed.

**Closed by bharathkkb** 2020-09-01 17:39 UTC
Labels: bug, upstream, wontfix
