### ISSUE TITLE
Error: Invalid count argument - gke.gcloud_delete_default_kube_dns_configmap/terraform-google-gcloud-1.4.1/main.tf line 57, in resource "random_id" "cache"

### ISSUE THREAD

**Issue by NeckBeardPrince** [terraform-google-modules/terraform-google-kubernetes-engine#633] opened 2020-08-18 16:00 UTC
* Replace the default kube-dns configmap if stub_domains are provided
I'm not using stub_domains but I get this error when doing a destroy.

```
Error: Invalid count argument

  on .terraform/modules/gke.gcloud_delete_default_kube_dns_configmap/terraform-google-gcloud-1.4.1/main.tf line 57, in resource "random_id" "cache":
  57:   count = (! local.skip_download) ? 1 : 0

The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.
```

**Comment by jai** [comment] 2020-08-20 07:18
I'm getting this error in our CI environment (Github runner) but not when running `terraform destroy` locally. Trying to figure out what's going on to cause the difference.

**Comment by bharathkkb** [comment] 2020-08-20 08:20
Hi @NeckBeardPrince @jai 
Are you setting `gcloud_skip_download`? If you could post a sample config, I can try reproducing.

**Comment by jai** [comment] 2020-08-20 10:25
Nope not setting `gcloud_skip_download`.

Here's a link to a failing test run (using Terratest): https://github.com/Honestbank/terraform-gcp-gke/runs/1006431810?check_suite_focus=true

**Comment by jai** [comment] 2020-08-20 12:23
This seems to be an issue with Terraform 0.13. Running locally with 0.12.29, 'terraform destroy' works fine with no issues.

**Comment by jai** [comment] 2020-08-24 04:37
@bharathkkb anything I can help re: troubleshooting? lmk

**Comment by bharathkkb** [comment] 2020-08-25 06:50
@jai thanks for the update and the link to the test.
- Is it possible to test `0.12.29` in the Action? 
- Could you try with the `v10.0.0` of this module? 

I will also give this a go this week :) 

@NeckBeardPrince are you also running into this with tf0.13?

**Comment by NeckBeardPrince** [comment] 2020-08-25 07:59
Yeah running 0.13. On Tue, Aug 25, 2020 at 1:50 AM, Bharath KKB <notifications@github.com> wrote:  
@jai thanks for the update and the link to the test.

Is it possible to test 0.12.29 in the Action?
Could you try with the v10.0.0 of this module?

I will also give this a go this week :)
@NeckBeardPrince are you also running into this with tf0.13?

**Comment by bharathkkb** [comment] 2020-08-28 04:24
@jai @NeckBeardPrince so this seems to have been a bug with `0.13.0`. I was able to reproduce it with `0.13.0` and when testing with `0.13.1` it seems to be fixed. Could you try this with `0.13.1`?
ref: https://github.com/hashicorp/terraform/issues/25851

**Comment by jai** [comment] 2020-08-28 05:42
Terraform Cloud is currently getting 403s from Github so I can't test it on there just yet 😂 #devopslife

I'll update soon when I try to run locally.

**Comment by bharathkkb** [comment] 2020-09-01 17:25
@jai @NeckBeardPrince closing this issue, feel free to reopen it warrants further investigation

**Closed by bharathkkb** 2020-09-01 17:25 UTC
Labels: bug, upstream
