### ISSUE TITLE
Can't Import Resources when this module has been used.

### ISSUE THREAD

**Issue by upodroid** [terraform-google-modules/terraform-google-kubernetes-engine#222] opened 2019-07-31 15:36 UTC
Hi

I'm having issues with this module. Something breaks when i try to import another resource in terraform but the errors never appear in plan or apply.

```
google_service_account.sa-list[0]: Importing from ID "projects/REDACTED/serviceAccounts/elasticsearch@REDACTED.iam.gserviceaccount.com"...
google_service_account.sa-list[0]: Import prepared!
  Prepared google_service_account for import
google_service_account.sa-list[0]: Refreshing state... [id=projects/REDACTED/serviceAccounts/elasticsearch@REDACTED.iam.gserviceaccount.com]

Error: Invalid index

  on .terraform/modules/gke/terraform-google-modules-terraform-google-kubernetes-engine-1394bde/modules/beta-public-cluster/main.tf line 252, in locals:
 252:   cluster_master_auth_list_layer2 = local.cluster_master_auth_list_layer1[0]
    |----------------
    | local.cluster_master_auth_list_layer1 is empty tuple

The given key does not identify an element in this collection value.


Error: Invalid operand

  on .terraform/modules/gke/terraform-google-modules-terraform-google-kubernetes-engine-1394bde/modules/beta-public-cluster/main.tf line 267, in locals:
 267:   cluster_network_policy_enabled             = ! local.cluster_type_output_network_policy_enabled[local.cluster_type]
    |----------------
    | local.cluster_type is "regional"
    | local.cluster_type_output_network_policy_enabled is object with 2 attributes

Unsuitable value for unary operand: a bool is required.


Error: Invalid operand

  on .terraform/modules/gke/terraform-google-modules-terraform-google-kubernetes-engine-1394bde/modules/beta-public-cluster/main.tf line 268, in locals:
 268:   cluster_http_load_balancing_enabled        = ! local.cluster_type_output_http_load_balancing_enabled[local.cluster_type]
    |----------------
    | local.cluster_type is "regional"
    | local.cluster_type_output_http_load_balancing_enabled is object with 2 attributes

Unsuitable value for unary operand: a bool is required.


Error: Invalid operand

  on .terraform/modules/gke/terraform-google-modules-terraform-google-kubernetes-engine-1394bde/modules/beta-public-cluster/main.tf line 269, in locals:
 269:   cluster_horizontal_pod_autoscaling_enabled = ! local.cluster_type_output_horizontal_pod_autoscaling_enabled[local.cluster_type]
Unsuitable value for unary operand: a bool is required.


Error: Invalid operand

  on .terraform/modules/gke/terraform-google-modules-terraform-google-kubernetes-engine-1394bde/modules/beta-public-cluster/main.tf line 272, in locals:
 272:   cluster_istio_enabled               = ! local.cluster_type_output_istio_enabled[local.cluster_type]
    |----------------
    | local.cluster_type is "regional"
    | local.cluster_type_output_istio_enabled is object with 2 attributes

Unsuitable value for unary operand: a bool is required.

```

This is my module configuration.

```
module "gke" {
  source                     = "terraform-google-modules/kubernetes-engine/google//modules/beta-public-cluster"
  project_id                 = var.project_id
  network_project_id         = var.xpn-project
  kubernetes_version         = "1.13.7-gke.8"
  name                       = "gitlab"
  regional                   = false
  region                     = var.region
  zones                      = ["${var.region}-b"]
  network                    = data.google_compute_network.main-net.name
  subnetwork                 = "main-net-uk"
  logging_service            = "logging.googleapis.com"
  monitoring_service         = "monitoring.googleapis.com"
  ip_range_pods              = "pods"
  ip_range_services          = "services"
  http_load_balancing        = true
  horizontal_pod_autoscaling = true
  kubernetes_dashboard       = false
  istio                      = true
  cloudrun                   = true
  network_policy             = false
  service_account            = "gke-sva@${var.project_id}.iam.gserviceaccount.com"

  node_pools = [
    {
      name               = "node-pool-a"
      machine_type       = "n1-standard-2"
      min_count          = 3
      max_count          = 5
      auto_repair        = true
      auto_upgrade       = true
      disk_size_gb       = 100
      disk_type          = "pd-ssd"
      image_type         = "UBUNTU"
      preemptible        = false
      initial_node_count = 3
    },
  ]

  node_pools_oauth_scopes = {
    all = []

    node-pool-a = [
      "https://www.googleapis.com/auth/cloud-platform",
    ]
  }

  node_pools_labels = {
    all = {}

    node-pool-a = {
      environment = "dev"
    }
  }

  node_pools_metadata = {
    all = {}

    node-pool-a = {
      node-pool-metadata-custom-value = "my-node-pool"
    }
  }

  node_pools_taints = {
    all         = []
    node-pool-a = []
  }

  node_pools_tags = {
    all         = []
    node-pool-a = []
  }
}
```

**Comment by anantasty** [comment] 2019-08-22 07:35
@upodroid can you please share your import statement please.

**Comment by anantasty** [comment] 2019-08-22 19:21
The following pull request addresses import issues
https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/242
This has been tested by importing a cluster as illustrated in the PR.

**Comment by upodroid** [comment] 2019-08-22 21:41
Hi

I have the above in my terraform resources, but I can't import any other resource in to the terraform state because it errors out as shown above. 

PR #242 shows a bug fix for importing a gke cluster. Run my above config in a Google project. Then try to import in to the terraform a bucket that exists in the project and see what happens. 

I can send a vid tomorrow morning when I'm at work.

**Comment by upodroid** [comment] 2019-08-24 13:57
Have a look at this screen recording.

https://imgur.com/yoonbmE

@morgante 
@anantasty

**Comment by upodroid** [comment] 2019-10-15 21:18
@omazin More information here

**Comment by aaron-lane** [comment] 2019-12-02 16:11
Duplicate of #14

**Closed by aaron-lane** 2019-12-02 16:11 UTC
Labels: bug
