### ISSUE TITLE
Existing GSA name is not used as lookup for the service account

### ISSUE THREAD

**Issue by johnraber** [terraform-google-modules/terraform-google-kubernetes-engine#1007] opened 2021-09-27 17:17 UTC
https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/v16.1.0/modules/workload-identity/main.tf#L35. 

_Change_ **account_id = var. name -> account_id = var. gcp_sa_name**

```
data "google_service_account" "cluster_service_account" {
  count = var.use_existing_gcp_sa ? 1 : 0

  account_id = var. gcp_sa_name

  project    = var.project_id
}
```

**Comment by morgante** [comment] 2021-09-27 17:29
Duplicate of #1002, which will be fixed in the next release. You can pin to `master` if you need a fix sooner.

**Closed by morgante** 2021-09-27 17:29 UTC
